config/routes.rb
Rails.application.routes.draw do
  root "urls#new"

  resource :url, only: [:create]
  get "/:slug", to: "urls#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ActiveRecord::Base
	validates_presence_of :url
	validates :url, format: URI::regexp(%w[http https])
	validates_uniqueness_of :slug
	validates_length_of :slug, within: 3..255, on: :create, message: "too long"

	before_validation :generate_slug
  
  def generate_slug
    self.slug = SecureRandom.uuid[0..5] if self.slug.nil? || self.slug.empty?
    true
	end
	
	def short_url
	  "#{ENV['ROOT_URL']}/#{self.slug}"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def not_found
		raise ActionController::RoutingError.new('Not Found')
	end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

  def new
  end

  def create
    @url = Url.new(url_params)
    @url.save
    respond_to do |format|
      format.html { redirect_to root_url }
      format.js
    end
  end

  def show
    @url = Url.find_by slug: params[:slug]
    not_found if @url.nil?
    redirect_to @url.url
  end

   
  private
  def url_params
    params.require(:url).permit(:url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Shortener</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/_shorten.html.erb
<div id='generated-url'>
  <p><b>Old url:</b> <a href='<%= url.url %>' target='_blank' rel='noopener noreferrer'><%= url.url %></a></p>
  <p><b>New url:</b> <a href='<%= url.short_url %>' target='_blank' rel='noopener noreferrer'><%= url.short_url %></a></p>
</div>

app/views/urls/create.js.erb
// Remove any previous appended html
document.querySelectorAll(".notice").forEach(el => el.remove());
document.querySelectorAll("#generated-url").forEach(el => el.remove());

<% if @url.valid? %>
  // Clear out input field
  document.getElementById('url_url').value = "";
  // Show old and new url
  var container = document.getElementById('shorten-container');
  container.insertAdjacentHTML('beforeend', "<%= j render(partial: 'urls/shorten', locals: { url: @url }) %>");
<% else %>
  var form = document.getElementById('shorten-form');
  <% @url.errors.full_messages.each do |message| %>
    form.insertAdjacentHTML('afterend', '<div class="notice"><%= escape_javascript(message)%></div>');
  <% end %>
<% end %>

app/views/urls/new.html.erb
<div class='container-fluid'>
  <div id='shorten-container'>
    <h4>Create a short url:</h4>
    <%= form_for :url, url: url_path, remote: true, html: { id: 'shorten-form' } do |f| %>
      <%= f.text_field :url, class: 'form-control shorten-url-field' %>
      <%= f.submit 'Shorten', class:'btn btn-primary' %>
    <% end %>
  </div>
</div>